<?php

namespace App\Modules\Accounting\Enums;

enum JournalVoucherTypeEnum: string
{
    case OPENING_STOCK = 'OPENING_STOCK';

    case OPENING_STOCK_REVERSAL = 'OPENING_STOCK_REVERSAL';

    case CUSTOMER_OPENING_BALANCE = 'CUSTOMER_OPENING_BALANCE';

    case SUPPLIER_OPENING_BALANCE = 'SUPPLIER_OPENING_BALANCE';

    case PURCHASE = 'PURCHASE';

    case PURCHASE_RETURN = 'PURCHASE_RETURN';

    case SALE = 'SALE';

    case SALES_RETURN = 'SALES_RETURN';

    case PAYMENT = 'PAYMENT';

    case RECEIPT = 'RECEIPT';

    case CUSTOMER_ADVANCE_ADJUSTMENT = 'CUSTOMER_ADVANCE_ADJUSTMENT';

    case SUPPLIER_ADVANCE_ADJUSTMENT = 'SUPPLIER_ADVANCE_ADJUSTMENT';

    case JOURNAL = 'JOURNAL';

    case REVERSAL = 'REVERSAL';
}