<?php

namespace App\Modules\Inventory\Enums;

enum InventoryTransactionTypeEnum: string
{
    case OPENING_STOCK = 'OPENING_STOCK';

    case PURCHASE = 'PURCHASE';

    case PURCHASE_RETURN = 'PURCHASE_RETURN';

    case SALE = 'SALE';

    case SALE_RETURN = 'SALE_RETURN';

    case STOCK_TRANSFER_IN = 'STOCK_TRANSFER_IN';

    case STOCK_TRANSFER_OUT = 'STOCK_TRANSFER_OUT';

    case STOCK_ADJUSTMENT_IN = 'STOCK_ADJUSTMENT_IN';

    case STOCK_ADJUSTMENT_OUT = 'STOCK_ADJUSTMENT_OUT';

    case MANUFACTURING_IN = 'MANUFACTURING_IN';

    case MANUFACTURING_OUT = 'MANUFACTURING_OUT';

    case STOCK_COUNT_GAIN = 'STOCK_COUNT_GAIN';
    case STOCK_COUNT_LOSS = 'STOCK_COUNT_LOSS';

    case DAMAGE = 'DAMAGE';
    case EXPIRY = 'EXPIRY';

    case RESERVED = 'RESERVED';
    case RELEASED = 'RELEASED';

    case REVERSAL_IN = 'REVERSAL_IN';
    case REVERSAL_OUT = 'REVERSAL_OUT';
}